version: '3.1'
services:
    api:
        container_name: lig_api
        build: .
        restart: always
        env_file:
        - .env
        ports:
        - "8080:8080"
        depends_on:
        - database
        networks:
        - lig-network

    database:
      container_name: lig_database
      build: ./initdb/.
      restart: always
      env_file:
        - .env
      volumes:
        - ./initdb:/docker-entrypoint-initdb.d
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - lig-network


volumes:
    postgres_data:

networks:
    lig-network: