version: '3.1'
services:
    api:
        container_name: lig_api
        build: .
        restart: always
        env_file:
        - .env
        ports:
        - "8080:8080"
        depends_on:
        - lig_database
        networks:
        - lig-network

    lig_database:
      container_name: lig_database
      build: ./initdb/.
      restart: always
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - lig-network


volumes:
    postgres_data:

networks:
    lig-network: