spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
              non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      open-in-view: true
  datasource:
    url: jdbc:postgresql://my-db:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
