spring:
  datasource:
    url: jdbc:postgresql://api_database:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
              non_contextual_creation: true
      generate-ddl: false
      open-in-view: true
