name: Lig-Esp Backend CI/CD
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build and Test maven
        run: mvn -B clean verify --file pom.xml


  build-and-push-docker-image-back:
    runs-on: ubuntu-latest
    needs:
      - test-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          env:
            DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            DATABASE_USER: ${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lig-esp-backend:latest

  build-and-push-docker-image-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./initdb/.
          file: ./initdb/Dockerfile
          env:
            POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
            POSTGRES_USER: ${{ secrets.DATABASE_USER }}
            POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lig-esp-database:latest

  build-and-push-docker-image-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./http-server/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lig-esp-proxy:latest


#  deploy-backend:
#    runs-on: ubuntu-latest
#    needs:
#      - build-and-push-docker-image-back
#      - test-backend
#    if: github.ref == 'refs/heads/main'